#*************************************************
#The following parameters are general run settings.
#*************************************************
DATAFILE: /Users/ewallwic/Dropbox_MIT/Aaron/Science/global_bh/global_bh/tables/test_signal_blackholes_nofg.csv #global signal data file
MPI: False #determine whether to use MPI
THREADS: 2 #number of threads to run
NSTEPS: 15000 #number of steps for each sampler
NWALKERS: 14 #number of MCMC walkers
PROJECT_NAME: test_analytic #name of output file.
NPTS_NOISE_EST: 20 #number of points to estimate std from
MPI: False #set to true if you are using open MPI
SAMPLE_BALL: .01
NBURN: 5000
#**************************************************
#We specify the default values of all model parameters
#in this section, including the parameters that we are
#not fitting. The next section specifies the names of
#parameters to fit.
#**************************************************
PARAMS: #this section specifies settings for all model parameters
    NU0: 86.08747350039043 #Analytic central frequency
    TAU: 1.0  #flatness parameter
    A: 0.6358635582880702 #Amplitude parameter
    W: 22.98761704590988  #Width parameter.
    NPOLY: 2
    APOLY0: 0.
    APOLY1: 0.
    #APOLY2: 0.
    #APOLY3: 0.
    #APOLY4: 0.
#**************************************************
#PARAMS2VARY is a list of parameter names that will
#be fit by the MCMC.
#**************************************************
PARAMS2VARY: #specify the names of parameters that will be fitted
    - NU0
    - TAU
    - A
    - W
    - TAU
    - APOLY0
    - APOLY1
    #- APOLY2
    #- APOLY3
    #- APOLY4
#**************************************************
#PRIORS specifies prior distributions on our fitting
#parameters.
#For each parameter, specify TYPE which can be
#UNIFORM, GAUSSIAN, or LOGNORMAL
#For UNIFORM priors, specify MIN and MAX value.
#For LOGNORMAL or GAUSSIAN priors, specify MEAN, VAR
#**************************************************
PRIORS:
  NU0:
    TYPE: UNIFORM
    MIN: 0.
    MAX: 1000.
  TAU:
    TYPE: UNIFORM
    MIN: -500.
    MAX: 1000.
  A:
    TYPE: UNIFORM
    MIN: 0.
    MAX: 1000.
  W:
    TYPE: UNIFORM
    MIN: 1.
    MAX: 1000.
  APOLY0:
    TYPE: UNIFORM
    MIN: -2500.
    MAX: 2500.
  APOLY1:
    TYPE: UNIFORM
    MIN: -2500.
    MAX: 2500.
 #APOLY2:
 #  TYPE: UNIFORM
 #  MIN: -2500
 #  MAX: 2500
 #APOLY3:
 #  TYPE: UNIFORM
 #  MIN: -10000
 #  MAX: 10000
 #APOLY4:
 #  TYPE: UNIFORM
 #  MIN: -10000
 #  MAX: 10000
