#*************************************************
#The following parameters are general run settings.
#*************************************************
DATAFILE: /Users/ewallwic/Dropbox_MIT/Aaron/Science/global_bh/global_bh/tables/test_signal_stars_supersimplefg.csv #global signal data file
MPI: False #determine whether to use MPI
THREADS: 2 #number of threads to run
NSTEPS: 5000 #number of steps for each sampler
NWALKERS: 16 #number of MCMC walkers
PROJECT_NAME: test_analytic #name of output file.
NPTS_NOISE_EST: 20 #number of points to estimate std from
MPI: False #set to true if you are using open MPI
SAMPLE_BALL: .01
NBURN: 1000
#**************************************************
#We specify the default values of all model parameters
#in this section, including the parameters that we are
#not fitting. The next section specifies the names of
#parameters to fit.
#**************************************************
PARAMS: #this section specifies settings for all model parameters
    NU0: 82. #Analytic central frequency
    TAU: .1  #flatness parameter
    A:  .175 #Amplitude parameter
    W:  20.7  #Width parameter.
    NPOLY: 1
    APOLY0: 2500.
#**************************************************
#PARAMS2VARY is a list of parameter names that will
#be fit by the MCMC.
#**************************************************
PARAMS2VARY: #specify the names of parameters that will be fitted
    - NU0
    - TAU
    - A
    - W
    - APOLY0
#**************************************************
#PRIORS specifies prior distributions on our fitting
#parameters.
#For each parameter, specify TYPE which can be
#UNIFORM, GAUSSIAN, or LOGNORMAL
#For UNIFORM priors, specify MIN and MAX value.
#For LOGNORMAL or GAUSSIAN priors, specify MEAN, VAR
#**************************************************
PRIORS:
  NU0:
    TYPE: UNIFORM
    MIN: 0.
    MAX: 1000.
  TAU:
    TYPE: UNIFORM
    MIN: 0.
    MAX: 1000.
  A:
    TYPE: UNIFORM
    MIN: 0.
    MAX: 1000.
  W:
    TYPE: UNIFORM
    MIN: 0.
    MAX: 1000.
  APOLY0:
    TYPE: UNIFORM
    MIN: -10000
    MAX: 10000
