CONFIG:
  MULTIPROCESS: False
  NPARALLEL: 12
  ZLOW: 6.
  ZHIGH: 120.
  FEEDBACK: True
  NTIMESGLOBAL: 200
  MASSLIMUNITS: KELVIN
PARAMS:
  NTIMES:
    TYPE: FIXED
    P0: 400
  ZMAX:
    TYPE: FIXED
    P0: 120.
  #Population II parameters
  ZMIN_POPII:
    TYPE: FIXED
    P0: 6.
  F_STAR_POPII:
    TYPE: FIXED
    P0: 0.1
  N_ION_POPII:
    TYPE: FIXED
    P0: 4400.
  ALPHA_X_POPII:
    TYPE: FIXED
    P0: 1.5
  FX_POPII:
    TYPE: FIXED
    P0: 1.
  LOG10_N_POPII:
    TYPE: FIXED
    P0: 20.
  F_ESC_POPII:
    TYPE: FIXED
    P0: 0.1
  TMIN_POPII:
    TYPE: FIXED
    P0: 10000.
  TMAX_POPII:
    TYPE: FIXED
    P0: 10000000000.
  #Population III parameters
  ZMIN_POPIII:
    TYPE: FIXED
    P0: 10.
  F_STAR_POPIII:
    TYPE: FIXED
    P0: 0.01
  ALPHA_X_POPIII:
    TYPE: FIXED
    P0: 1.5
  FX_POPIII:
    TYPE: FIXED
    P0: 1.
  LOG10_N_POPIII:
    TYPE: FIXED
    P0: 23.
  F_ESC_POPIII:
    TYPE: FIXED
    P0: 0.1
  N_ION_POPIII:
    TYPE: FIXED
    P0: 30000.
  TMIN_POPIII:
    TYPE: FIXED
    P0: 10000.
  TMAX_POPIII:
    TYPE: FIXED
    P0: 10000.
  #Formation Parameters
  ZMIN:
    TYPE: FIXED
    P0: 6.
  Z_SEED_MIN:
    TYPE: FIXED
    P0: 10.
  TAU_GROW:
    TYPE: FIXED
    P0: 0.045
  TAU_FEEDBACK:
    TYPE: FIXED
    P0: 0.1
  TMIN_HALO:
    TYPE: FIXED
    P0: 2000.
  TMAX_HALO:
    TYPE: FIXED
    P0: 10000.
  FS:
    TYPE: FIXED
    P0: 1.5e-5
  #X-ray parameters
  GBOL: #fraction of Eddington between 2-10 keV
    TYPE: FIXED
    P0: 0.03
  ALPHA_X: #X-ray spectral index
    TYPE: FIXED
    P0: 0.9
  LOG10_N: #Hydrogen column depth
    TYPE: FIXED
    P0: 23.5
  #Optical Parameters
  ALPHA_OX:
    TYPE: FIXED
    P0: 1.6
  ALPHA_O1:
    TYPE: FIXED
    P0: 0.61 #Spectral index blue of 13.6 eV
  ALPHA_O2:
    TYPE: FIXED
    P0: 1.71
  F_ESC: #Ly-C escape fraction
    TYPE: FIXED
    P0: 0.1
  #Radio parameters
  FLOUD: #Fraction of black holes that are radio loud
    TYPE: FIXED
    P0: 0.1
  R_MEAN: #Mean of radio loudness distribution
    TYPE: FIXED
    P0: 2.8
  R_STD: #Standard deviation of Radio distribution
    TYPE: FIXED
    P0: 1.1
  ALPHA_R: #Radio Specral Index
    TYPE: FIXED
    P0: 0.6
