CONFIG:
  MULTIPROCESS: False
  NPARALLEL: 2
  ZLOW: 7.
  ZHIGH: 70.
  FEEDBACK: True
  NTIMESGLOBAL: 100
  MASSLIMUNITS: KELVIN
  MFMODEL: tinker08
  MFDEFF: 200m
  DENSITYMETHOD: ANALYTIC
  COMPUTEBACKGROUNDS: True
  OUTPUTNAME: fiducial_bh_model_lowz_obscured_no_radio
  COMPUTE_FEEDBACK: False
  LW_FEEDBACK: False
PARAMS:
  EPS:
    TYPE: FLOAT
    P0: 0.05
  TAU_DELAY:
    TYPE: FLOAT
    P0: 0.0
  TAU_DELAY_POPII:
    TYPE: FLOAT
    P0: 0.00
  TAU_DELAY_POPIII:
    TYPE: FLOAT
    P0: 0.00
  NTIMES:
    TYPE: FLOAT
    P0: 400
  ZMAX:
    TYPE: FLOAT
    P0: 80.
  #Population II parameters
  ZMIN_POPII:
    TYPE: FLOAT
    P0: 6.
  F_STAR_POPII:
    TYPE: FLOAT
    P0: 0.1
  N_ION_POPII:
    TYPE: FLOAT
    P0: 2000.
  ALPHA_X_POPII:
    TYPE: FLOAT
    P0: 1.5
  FX_POPII:
    TYPE: FLOAT
    P0: 1.
  LOG10_N_POPII:
    TYPE: FLOAT
    P0: 19.
  F_ESC_POPII:
    TYPE: FLOAT
    P0: 0.1
  TMIN_POPII:
    TYPE: FLOAT
    P0: 8.0e4
  TMAX_POPII:
    TYPE: FLOAT
    P0: 1.0e8
  #Population III parameters
  ZMIN_POPIII:
    TYPE: FLOAT
    P0: 10.
  F_STAR_POPIII:
    TYPE: FLOAT
    P0: 1.0e-10
  ALPHA_X_POPIII:
    TYPE: FLOAT
    P0: 1.5
  FX_POPIII:
    TYPE: FLOAT
    P0: 1.
  LOG10_N_POPIII:
    TYPE: FLOAT
    P0: 19.
  F_ESC_POPIII:
    TYPE: FLOAT
    P0: 0.1
  N_ION_POPIII:
    TYPE: FLOAT
    P0: 3.0e4
  TMIN_POPIII:
    TYPE: FLOAT
    P0: 8.0e3
  TMAX_POPIII:
    TYPE: FLOAT
    P0: 1.0e4
  #Formation Parameters
  ZMIN:
    TYPE: FLOAT
    P0: 6.
  Z_SEED_MIN:
    TYPE: FLOAT
    P0: 16.
  TAU_GROW:
    TYPE: FLOAT
    P0: 4.5
  TAU_FEEDBACK:
    TYPE: FLOAT
    P0: 1.
  TMIN_HALO:
    TYPE: FLOAT
    P0: 2.0e3
  TMAX_HALO:
    TYPE: FLOAT
    P0: 1.0e8
  FBH:
    TYPE: FLOAT
    P0: 5.0e-5
  #X-ray parameters
  GBOL: #fraction of Eddington between 2-10 keV
    TYPE: FLOAT
    P0: 0.006
  ALPHA_X: #X-ray spectral index
    TYPE: FLOAT
    P0: 0.9
  LOG10_N: #Hydrogen column depth
    TYPE: FLOAT
    P0: 23.5
  #Optical Parameters
  ALPHA_OX:
    TYPE: FLOAT
    P0: 1.6
  ALPHA_O1:
    TYPE: FLOAT
    P0: 0.61 #Spectral index blue of 13.6 eV
  ALPHA_O2:
    TYPE: FLOAT
    P0: 1.71
  F_ESC: #Ly-C escape fraction
    TYPE: FLOAT
    P0: 0.1
  #Radio parameters
  FLOUD: #Fraction of black holes that are radio loud
    TYPE: FLOAT
    P0: 0.0
  R_MEAN: #Mean of radio loudness distribution
    TYPE: FLOAT
    P0: 2.8
  R_STD: #Standard deviation of Radio distribution
    TYPE: FLOAT
    P0: 1.1
  ALPHA_R: #Radio Specral Index
    TYPE: FLOAT
    P0: 0.6
